# Generated by Django 4.2 on 2023-04-26 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenue', models.CharField(max_length=128)),
                ('auteur', models.CharField(blank=True, default='anonyme', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(max_length=128)),
                ('contenue', models.CharField(max_length=128)),
                ('fichier', models.FileField(blank=True, upload_to='document/competition')),
                ('classe', models.CharField(choices=[('3eme', '3eme'), ('2nd', '2nd'), ('premier', 'premier'), ('terminal', 'terminal')], default='', max_length=128)),
                ('date_debut_Competion', models.DateField()),
                ('date_fin_Competion', models.DateField()),
                ('poste', models.CharField(default='MOCTA-EDUCATION', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=128)),
                ('titre', models.CharField(default='bon à savoir', max_length=128)),
                ('contenue', models.TextField(blank=True)),
                ('fichier', models.FileField(blank=True, upload_to='document/cours/')),
            ],
        ),
        migrations.CreateModel(
            name='Epreuves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=128)),
                ('titre', models.CharField(blank=True, default='bon à savoir', max_length=128)),
                ('contenue', models.TextField(blank=True)),
                ('fichier', models.FileField(blank=True, upload_to='document/epreuve/')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=128)),
                ('niveauR', models.CharField(max_length=128)),
                ('filiere', models.CharField(max_length=128)),
                ('telephone', models.IntegerField()),
                ('matiere_dispenserR', models.CharField(max_length=200)),
                ('classeE', models.CharField(choices=[('3eme', '3eme'), ('2nd', '2nd'), ('premier', 'premier'), ('terminal', 'terminal')], default='', max_length=128)),
                ('etablissement', models.CharField(blank=True, max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('salaireR', models.IntegerField(default=0)),
                ('pays', models.CharField(max_length=128)),
                ('ville', models.CharField(max_length=128)),
                ('quatier', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('eleve', 'eleve'), ('repetiteur', 'repetiteur')], default='eleve', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ReponseCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse1', models.TextField()),
                ('reponse2', models.FileField(upload_to='document/reponse/reponse_competition')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toto5', to='core.utilisateurs')),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenue', models.CharField(max_length=128)),
                ('fichier', models.FileField(blank=True, upload_to='document/reponse')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.utilisateurs')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toto3', to='core.utilisateurs')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toto4', to='core.utilisateurs')),
            ],
        ),
        migrations.CreateModel(
            name='Preoccupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenue', models.CharField(max_length=128)),
                ('fichier', models.FileField(blank=True, upload_to='document/preoccupation')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toto1', to='core.utilisateurs')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toto2', to='core.utilisateurs')),
            ],
        ),
    ]
