# Generated by Django 4.2 on 2023-04-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_preoccupation_auteur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citations',
            name='date_publication',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='date_publication',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cours',
            name='date_publication',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='epreuves',
            name='date_publication',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='preoccupation',
            name='date_publication',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reponse',
            name='date_publication',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reponsecompetition',
            name='date_publication',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='date_inscription',
            field=models.DateField(null=True),
        ),
    ]
